CREATE TABLE users (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    surname VARCHAR(255),
    personID VARCHAR(12) UNIQUE NOT NULL,
    uuid VARCHAR(255) UNIQUE NOT NULL
);